//{{NO_DEPENDENCIES}}
#pragma once

#define IDD_MFC_GLOWINGBUTTONTEST_DIALOG 102

#define IDC_BTN_NORMAL          1001
#define IDC_BTN_RAINBOW         1002
#define IDC_BTN_ROUNDED         1003
#define IDC_BTN_DISABLED        1004
#define IDC_BTN_TOGGLE_RAINBOW  1005
#define IDC_BTN_NO_BORDER       1006
#define IDC_BTN_BLUE_BORDER     1007
#define IDC_BTN_GREEN_HOVER     1008
#define IDC_BTN_ORANGE_PRESS    1009
#define IDC_BTN_PILL            1010
#define IDC_BTN_FLAT_DARK       1011
#define IDC_BTN_ACCENT          1012

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
